### ISSUE TITLE
coffeelint.json being ignored with symlinked files

### ISSUE THREAD

**Issue by febLey** [AtomLinter/linter-coffeelint#43]
Hello there,
there are numerous issues where the coffeelint.json isn't recognized.
I've got a similar issue, but the folder with my coffeescript files is symlinked into my project folder.
The coffeelint.json is in the project folder.

![62fa7f9e-1e52-11e5-9a2d-2e419b229ed9](https://cloud.githubusercontent.com/assets/1727958/8541237/fb07d7c4-248c-11e5-9426-f037f2973e94.png)

**Comment by AsaAyers** [comment]
> there are numerous issues where the coffeelint.json isn't recognized.

Where exactly are these numerous issues?

![selection_134](https://cloud.githubusercontent.com/assets/324999/8546066/8464c6ae-2482-11e5-9025-9c82abd25ee1.png)

**Comment by AsaAyers** [comment]
Try running the coffeelint from the command line. This will verify whether the bug is `coffeelint` or `linter-coffeelint`. Also `coffeelint` will warn when there is a syntax error in the config file, but currently `linter-coffeelint` doesn't. 

I verified that `linter-coffeelint` does work when `coffeelint.json` is a symlink.

**Comment by febLey** [comment]
I'm Sorry, my initial post sounded harsh.
I meant that multiple users had problems with the coffeelint.json, but they're solved by now.

I followed your advise and tried it on the command line.
coffeelint doesn't throw an error, so it seems like there's a problem with the plugin.
This must be connected to the fact that i use symlinks.

**Comment by AsaAyers** [comment]
I was trying to symlink `coffeelint.json`, but I see from your screenshot that you're linking your code into a project instead.

If you open up the console in atom and run `atom.workspace.getActiveTextEditor().getPath()` you'll see it doesn't involve your symlink. It's the actual path to the file. Since that's the path we have, that is what `linter-coffeelint` is going to search to find a configuration file.

Sorry, I think if you want to see a fix for this you'll need to get Atom to provide the symlinked path.
